load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

RULES_JVM_EXTERNAL_TAG = "3.2"

RULES_JVM_EXTERNAL_SHA = "82262ff4223c5fda6fb7ff8bd63db8131b51b413d26eb49e3131037e79e324af"

http_archive(
    name = "rules_jvm_external",
    sha256 = RULES_JVM_EXTERNAL_SHA,
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)

load("@rules_jvm_external//:defs.bzl", "maven_install")

VER = {
    "JUNIT_JUPITER": "5.6.0",
    "JUNIT_PLATFORM": "1.6.0",
}

maven_install(
    artifacts = [
        "org.junit.jupiter:junit-jupiter-api:%s" % VER["JUNIT_JUPITER"],
        "org.junit.jupiter:junit-jupiter-engine:%s" % VER["JUNIT_JUPITER"],
        "org.junit.platform:junit-platform-console:%s" % VER["JUNIT_PLATFORM"],
    ],
    repositories = [
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)
